import React from "react";
import { Section } from "../../GlobalStyle.styled";
import { AboutContainer } from "./About.styled";
import { ReactComponent as Cross } from "../../icons/cross.svg";
import Banner from "../Banner/Banner";

function About() {
    return (
        <Section style={{ position: "relative" }}>
            <AboutContainer>
                <h2>
                    a Story that started with <span>one simple ape</span>
                </h2>
                <p>
                    WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS
                    IS HOW THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
                </p>
                <Cross
                    style={{ width: "24px", height: "24px", fill: "white" }}
                />
                <p>
                    EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY.
                    ARTS ARE RANDOMLY GENERATED BY USERS
                </p>
                <Banner />
            </AboutContainer>
        </Section>
    );
}

export default About;
