import React from "react";
import { Section } from "../../GlobalStyle.styled";
import { AboutContainer, FirstDiv, SecondDiv } from "./About.styled";
import { ReactComponent as Cross } from "../../icons/cross.svg";
import Banner from "../Banner/Banner";
import { useMedia } from "use-media";
import about from "../../exports/about";
import { root } from "../../stylesheets/root";

function About() {
    const isTabScreen = useMedia({ minWidth: "768px" });

    return (
        <Section style={{ position: "relative" }}>
            <AboutContainer>
                <FirstDiv>
                    <h2>
                        a Story that started with{" "}
                        <span>one simple {"\n"}ape</span>
                    </h2>
                    <p>
                        WHO GOT{"\n"} FED UP WITH BORING AND HYPOCRITIC
                        COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC
                        JOURNEY ON THE{isTabScreen && <br />} YACHT
                    </p>
                </FirstDiv>
                <SecondDiv>
                    <Cross />
                    <p>
                        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE
                        JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS
                    </p>
                </SecondDiv>
                <img
                    srcSet={`
                          ${about.aboutMob1x} 320w,
                          ${about.aboutMob2x} 640w,
                          ${about.aboutTab1x} 768w,
                          ${about.aboutTab2x} 1536w,
                          ${about.aboutDesk1x} 1280w,
                          ${about.aboutDesk2x} 2560w
                        `}
                    sizes={`
                        (min-width: ${root.breakpoints.minMobile}) and (max-width: calc(${root.breakpoints.tablet} - 1px)) 216px,
                        (min-width: ${root.breakpoints.tablet}) and (max-width: calc(${root.breakpoints.desktop} - 1px)) 768px,
                          1280px
                        `}
                    src={about.aboutDesk1x}
                    alt={about.alt}
                />
                <Banner />
            </AboutContainer>
        </Section>
    );
}

export default About;
