import React from "react";
import { Section } from "../../GlobalStyle.styled";
import { AboutContainer, FirstDiv, SecondDiv } from "./About.styled";
import { ReactComponent as Cross } from "../../icons/cross.svg";
import Banner from "../Banner/Banner";
import { useMedia } from "use-media";

function About() {
    const isTabScreen = useMedia({ minWidth: "768px" });

    return (
        <Section style={{ position: "relative" }}>
            <AboutContainer>
                <FirstDiv>
                    <h2>
                        a Story that started with{" "}
                        <span>one simple {"\n"}ape</span>
                    </h2>
                    <p>
                        WHO GOT{"\n"} FED UP WITH BORING AND HYPOCRITIC
                        COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC
                        JOURNEY ON THE{isTabScreen && <br />} YACHT
                    </p>
                </FirstDiv>
                <SecondDiv>
                    <Cross />
                    <p>
                        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE
                        JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS
                    </p>
                </SecondDiv>
                <Banner />
            </AboutContainer>
        </Section>
    );
}

export default About;
